[project]
name = "aws-mcp-server"
version = "0.2.0"
description = "AWS MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["boto3>=1.37.18", "mcp[cli]>=1.5.0"]


[project.scripts]
"aws-mcp-server" = "aws_mcp_server.server:main"
